In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [41]:
dataset = pd.read_csv(r"C:\Users\Rads Gupta\Desktop\Machine Learning A-Z\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [42]:
from sklearn.preprocessing import Imputer
imputer=Imputer(missing_values='NaN', strategy="mean", axis=0)
imputer=imputer.fit(X[:,1:3])
print(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
print(X[:,1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]
[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


In [43]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

In [44]:
X[:,1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, 63777.77777777778],
       [35.0, 58000.0],
       [38.77777777777778, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [45]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [46]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [47]:
labelencoder_x=LabelEncoder()

In [48]:
X[:,0]=labelencoder_x.fit_transform(X[:,0])

In [49]:

X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [53]:
y[:-1]=labelencoder_x.fit_transform(y[:-1])

In [54]:
y[:-1]

array([0, 1, 0, 0, 1, 1, 0, 1, 0], dtype=object)

In [55]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 'Yes'], dtype=object)

In [57]:
onehotencooder=OneHotEncoder(categorical_features=[0])

In [58]:
X=onehotencooder.fit_transform(X).toarray()

In [68]:
z=X.astype(int)

In [64]:
from sklearn.cross_validation import  train_test_split

In [75]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=4)

In [76]:
xtrain.astype(int)

array([[    0,     1,     0,    40, 63777],
       [    1,     0,     0,    37, 67000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    1,     0,     0,    35, 58000],
       [    1,     0,     0,    48, 79000]])

In [77]:
xtrain

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.70000000e+01,   6.70000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04]])

In [78]:
xtest

array([[  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04]])

In [83]:
ytrain

array([1, 'Yes', 0, 0, 0, 1, 1, 1], dtype=object)

In [80]:
ytest

array([0, 0], dtype=object)

In [82]:
xtrain.astype(int)

array([[    0,     1,     0,    40, 63777],
       [    1,     0,     0,    37, 67000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    1,     0,     0,    35, 58000],
       [    1,     0,     0,    48, 79000]])