In [1]:
from sklearn import datasets
import numpy as np

In [2]:
from sklearn.svm import SVC

In [39]:
from scipy import misc

In [40]:
pwd


'C:\\Users\\Rads Gupta'

In [88]:
myimage=misc.imread("1.png")

In [89]:
myimage.shape

(648, 1152, 3)

In [90]:
mynewimage=misc.imresize(myimage,(8,8))

In [91]:
mynewimage.shape

(8, 8, 3)

In [92]:
mynewimage.dtype

dtype('uint8')

In [93]:
mydata=datasets.load_digits()

In [94]:
mynewimage=mynewimage.astype(mydata.images.dtype)

In [95]:
mynewimage.dtype

dtype('float64')

In [96]:
mynewimage

array([[[ 216.,  216.,  216.],
        [ 181.,  181.,  181.],
        [ 241.,  241.,  241.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.]],

       [[ 138.,  138.,  138.],
        [  37.,   37.,   37.],
        [ 211.,  211.,  211.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.]],

       [[ 134.,  134.,  134.],
        [  31.,   31.,   31.],
        [ 210.,  210.,  210.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.]],

       [[ 151.,  151.,  151.],
        [  62.,   62.,   62.],
        [ 217.,  217.,  217.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.],
        [ 255.,  255.,  255.]],



In [97]:
mynewimage=misc.bytescale(mynewimage,high=16,low=0)

In [98]:
mynewimage

array([[[13, 13, 13],
        [11, 11, 11],
        [15, 15, 15],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16]],

       [[ 8,  8,  8],
        [ 0,  0,  0],
        [13, 13, 13],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16]],

       [[ 7,  7,  7],
        [ 0,  0,  0],
        [13, 13, 13],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16]],

       [[ 9,  9,  9],
        [ 2,  2,  2],
        [13, 13, 13],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16]],

       [[15, 15, 15],
        [14, 14, 14],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16]],

       [[16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],
        [16, 16, 16],


In [99]:
mynewimage=mynewimage.astype(mydata.images.dtype)

In [100]:
mynewimage.dtype

dtype('float64')

In [101]:
len(mynewimage)

8

In [102]:
mydata.images[-1]

array([[  0.,   0.,  10.,  14.,   8.,   1.,   0.,   0.],
       [  0.,   2.,  16.,  14.,   6.,   1.,   0.,   0.],
       [  0.,   0.,  15.,  15.,   8.,  15.,   0.,   0.],
       [  0.,   0.,   5.,  16.,  16.,  10.,   0.,   0.],
       [  0.,   0.,  12.,  15.,  15.,  12.,   0.,   0.],
       [  0.,   4.,  16.,   6.,   4.,  16.,   6.,   0.],
       [  0.,   8.,  16.,  10.,   8.,  16.,   8.,   0.],
       [  0.,   1.,   8.,  12.,  14.,  12.,   1.,   0.]])

In [103]:
xtest=[]

In [104]:
for eachRow in mynewimage:
    for eachPixel in eachRow:
        xtest.append(sum(eachPixel)/3.0)
    

In [105]:

xfeature=mydata.data

In [106]:
ytarget=mydata.target

In [107]:
mysvc=SVC(gamma=0.001)

In [108]:
mymodel=mysvc.fit(xfeature,ytarget)

In [109]:
mymodel.predict(xtest)

C:\Users\Rads Gupta\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])