In [4]:
import numpy as np

In [5]:
from sklearn import datasets

In [6]:
mydata=datasets.load_iris()

In [7]:
mydata

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [8]:
i=mydata.data

In [9]:
i.shape

(150, 4)

In [10]:
t=mydata.target

In [11]:
t.shape

(150,)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest=train_test_split(i,t,test_size=0.4,random_state=42)

In [14]:
xtrain.shape

(90, 4)

In [15]:
xtrain

array([[ 6.3,  2.7,  4.9,  1.8],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 5.6,  2.7,  4.2,  1.3],
       [ 5.1,  3.4,  1.5,  0.2],
       [ 5.7,  3. ,  4.2,  1.2],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 6.2,  2.9,  4.3,  1.3],
       [ 5.7,  2.5,  5. ,  2. ],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 6. ,  3. ,  4.8,  1.8],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 5.4,  3. ,  4.5,  1.5],
       [ 6.2,  3.4,  5.4,  2.3],
       [ 5.5,  2.3,  4. ,  1.3],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 5. ,  2.3,  3.3,  1. ],
       [ 6.4,  2.7,  5.3,  1.9],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 5. ,  3.2,  1.2,  0.2],
       [ 5.5,  2.4,  3.8,  1.1],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.8,  2.8,  5.1,  2.4],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 5

In [16]:
ytrain

array([2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0,
       1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0,
       2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0,
       1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn=KNeighborsClassifier(n_neighbors=3)

In [19]:
mymodel=knn.fit(xtrain,ytrain)

In [20]:
yp=mymodel.predict(xtest)

In [21]:
yp

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0,
       2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1,
       1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1])

In [22]:
from sklearn import metrics

In [23]:
metrics.accuracy_score(ytest,yp)

0.98333333333333328

In [24]:
import pandas as pd

In [25]:
mydf=pd.DataFrame({"Av":ytest,"Pv":yp})

In [26]:
mydf

Av  Pv
0    1   1
1    0   0
2    2   2
3    1   1
4    1   1
5    0   0
6    1   1
7    2   2
8    1   1
9    1   1
10   2   2
11   0   0
12   0   0
13   0   0
14   0   0
15   1   1
16   2   2
17   1   1
18   1   1
19   2   2
20   0   0
21   2   2
22   0   0
23   2   2
24   2   2
25   2   2
26   2   2
27   2   2
28   0   0
29   0   0
30   0   0
31   0   0
32   1   1
33   0   0
34   0   0
35   2   2
36   1   1
37   0   0
38   0   0
39   0   0
40   2   2
41   1   1
42   1   1
43   0   0
44   0   0
45   1   1
46   2   1
47   2   2
48   1   1
49   2   2
50   1   1
51   2   2
52   1   1
53   0   0
54   2   2
55   1   1
56   0   0
57   0   0
58   0   0
59   1   1