In [179]:
import numpy as np

In [180]:
from sklearn import datasets

In [181]:
mydata=datasets.load_iris()

In [182]:
mydata

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [183]:
i=mydata.data

In [184]:
i.shape

(150, 4)

In [185]:
t=mydata.target

In [186]:
t.shape

(150,)

In [187]:
from sklearn.model_selection import train_test_split

In [188]:
xtrain,xtest,ytrain,ytest=train_test_split(i,t,test_size=0.4,random_state=50)

In [189]:
xtrain.shape

(90, 4)

In [190]:
xtrain

array([[ 7.7,  3.8,  6.7,  2.2],
       [ 6.4,  2.9,  4.3,  1.3],
       [ 6.3,  2.9,  5.6,  1.8],
       [ 5. ,  3.5,  1.3,  0.3],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 6. ,  2.9,  4.5,  1.5],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.5,  2.3,  4. ,  1.3],
       [ 5.1,  3.8,  1.9,  0.4],
       [ 7.3,  2.9,  6.3,  1.8],
       [ 6.4,  3.1,  5.5,  1.8],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 6.4,  2.8,  5.6,  2.1],
       [ 5.6,  2.5,  3.9,  1.1],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 6.3,  2.3,  4.4,  1.3],
       [ 5.2,  4.1,  1.5,  0.1],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 6.9,  3.1,  4.9,  1.5],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.9,  3. ,  4.2,  1.5],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 6. ,  2.7,  5.1,  1.6],
       [ 4.8,  3. ,  1.4,  0.3],
       [ 5.5,  2.6,  4.4,  1.2],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 7.2,  3. ,  5.8,  1.6],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 6

In [191]:
ytrain

array([2, 1, 2, 0, 0, 2, 1, 0, 1, 0, 2, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 2, 2, 2, 1, 2, 0, 2, 0, 1, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2,
       1, 2, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2, 0, 1, 2, 0, 0,
       1, 2, 1, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 2, 1, 2, 0, 2, 2])

In [192]:
from sklearn.naive_bayes import GaussianNB

In [193]:

gnb=GaussianNB()

In [194]:
mymodel=gnb.fit(xtrain,ytrain)

In [195]:
yp=mymodel.predict(xtest)

In [196]:
yp

array([1, 1, 0, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 2, 1, 0, 1, 0, 1, 2, 2, 1, 0,
       2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 2, 0, 2, 0,
       0, 0, 2, 2, 1, 0, 0, 1, 2, 1, 1, 0, 0, 2])

In [197]:
from sklearn import metrics

In [198]:
metrics.accuracy_score(ytest,yp)

0.94999999999999996

In [199]:
import pandas as pd

In [200]:
mydf=pd.DataFrame({"Av":ytest,"Pv":yp})

In [201]:
mydf

Av  Pv
0    1   1
1    1   1
2    0   0
3    0   0
4    2   2
5    2   2
6    2   2
7    0   0
8    0   0
9    1   1
10   0   0
11   2   2
12   0   0
13   2   2
14   1   1
15   0   0
16   1   1
17   0   0
18   1   1
19   1   2
20   2   2
21   1   1
22   0   0
23   2   2
24   1   1
25   2   2
26   1   2
27   1   1
28   1   1
29   2   2
30   2   2
31   1   1
32   1   1
33   2   2
34   0   0
35   0   0
36   1   1
37   2   1
38   1   1
39   0   0
40   0   0
41   1   1
42   2   2
43   0   0
44   2   2
45   0   0
46   0   0
47   0   0
48   2   2
49   2   2
50   1   1
51   0   0
52   0   0
53   1   1
54   2   2
55   1   1
56   1   1
57   0   0
58   0   0
59   2   2

# Using Bernoulli's Distribution

In [202]:
from sklearn.naive_bayes import BernoulliNB

In [203]:
bnb=BernoulliNB()

In [204]:
mymodel1=bnb.fit(xtrain,ytrain)

In [205]:
yp1=mymodel1.predict(xtest)

In [206]:
yp1

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [207]:
from sklearn import metrics

In [208]:
metrics.accuracy_score(ytest,yp1)

0.29999999999999999

In [209]:
import pandas as pd

In [210]:
mydf2=pd.DataFrame({"Av1":ytest,"Pv1":yp1})

In [211]:
mydf2

Av1  Pv1
0     1    2
1     1    2
2     0    2
3     0    2
4     2    2
5     2    2
6     2    2
7     0    2
8     0    2
9     1    2
10    0    2
11    2    2
12    0    2
13    2    2
14    1    2
15    0    2
16    1    2
17    0    2
18    1    2
19    1    2
20    2    2
21    1    2
22    0    2
23    2    2
24    1    2
25    2    2
26    1    2
27    1    2
28    1    2
29    2    2
30    2    2
31    1    2
32    1    2
33    2    2
34    0    2
35    0    2
36    1    2
37    2    2
38    1    2
39    0    2
40    0    2
41    1    2
42    2    2
43    0    2
44    2    2
45    0    2
46    0    2
47    0    2
48    2    2
49    2    2
50    1    2
51    0    2
52    0    2
53    1    2
54    2    2
55    1    2
56    1    2
57    0    2
58    0    2
59    2    2

# using multinomial distribution 

In [212]:
from sklearn.naive_bayes import MultinomialNB

In [213]:
mnb=MultinomialNB()

In [214]:
mymodel2=mnb.fit(xtrain,ytrain)

In [215]:
yp2=mymodel2.predict(xtest)

In [216]:
e=metrics.accuracy_score(ytest,yp2)

In [217]:
e

0.80000000000000004