In [7]:
a="rads"

In [8]:
a

'rads'

In [9]:
type(a)

str

In [10]:
b=2
c=8
d=b*c

In [11]:
d

16

In [14]:
d=['h',6,9,'k']

In [15]:
type(d)

list

In [16]:
d

['h', 6, 9, 'k']

In [23]:
e={"name":['rads','gauri','khushi'],"age":[1,2,3],"xbc":[2,3,4]}

In [24]:
type(e)

dict

In [25]:
e

{'age': [1, 2, 3], 'name': ['rads', 'gauri', 'khushi'], 'xbc': [2, 3, 4]}

In [26]:
import numpy as np

In [35]:
a=np.array([1,3,6,9,8,10],dtype=float)

In [36]:
a

array([  1.,   3.,   6.,   9.,   8.,  10.])

In [37]:
type(a)

numpy.ndarray

In [38]:
a.ndim

1

In [39]:
a.shape

(6,)

In [40]:
len(a)

6

In [41]:
a.itemsize

8

In [42]:
a.dtype

dtype('float64')

In [43]:
a[len(a)-1]

10.0

In [44]:
a[-1]

10.0

In [48]:
a[:]

array([  1.,   3.,   6.,   9.,   8.,  10.])

In [58]:
a[-3:-1]

array([ 9.,  8.])

In [61]:
a[1: :2]

array([  3.,   9.,  10.])

In [62]:
a=np.array([[3,4,5],[4,5,8],[9,8,7]])

In [63]:
a

array([[3, 4, 5],
       [4, 5, 8],
       [9, 8, 7]])

In [64]:
a.sum()

53

In [65]:
a.sum(axis=0)

array([16, 17, 20])

In [66]:
a[0]

array([3, 4, 5])

In [67]:
type(a)

numpy.ndarray

In [69]:
a.shape

(3, 3)

In [71]:
a[:,0]

array([3, 4, 9])

In [72]:
a.T

array([[3, 4, 9],
       [4, 5, 8],
       [5, 8, 7]])

In [74]:
a.sum()

53

In [75]:
a[0:2]

array([[3, 4, 5],
       [4, 5, 8]])

In [76]:
a=np.zeros([4,4])

In [77]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [78]:
a=np.ones([4,4])

In [79]:
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [80]:
b=np.eye(3)

In [81]:
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [4]:
import pandas as pd

In [5]:
a=pd.Series([1,2,3,4,5,6,7],index=["one","a","b","c","d","e","f"])

In [6]:
a

one    1
a      2
b      3
c      4
d      5
e      6
f      7
dtype: int64

In [7]:
a.values

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [8]:
a

one    1
a      2
b      3
c      4
d      5
e      6
f      7
dtype: int64

In [9]:
type(a)

pandas.core.series.Series

In [10]:
mydata=pd.DataFrame({"name":["abc","def","ghi"],"age":[2,4,8],"marks":[23,45,67]})

In [96]:
mydata

age  marks name
0    2     23  abc
1    4     45  def
2    8     67  ghi

In [104]:
mydata.head(-1)

age  marks name
0    2     23  abc
1    4     45  def

In [103]:
mydata.describe()

age  marks
count  3.000000    3.0
mean   4.666667   45.0
std    3.055050   22.0
min    2.000000   23.0
25%    3.000000   34.0
50%    4.000000   45.0
75%    6.000000   56.0
max    8.000000   67.0

In [105]:
mydata.shape

(3, 3)

mydata.keys

In [12]:
mydata.head(-1)

age  marks name
0    2     23  abc
1    4     45  def

In [22]:
mydata.head(-2)

age  marks name
0    2     23  abc