In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.naive_bayes import MultinomialNB

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
mydata = pd.read_csv(r"C:\Users\Rads Gupta\Desktop\SMSSpamCollection",sep="\t",header=0,names=["status",'message'])

In [7]:
mydata.head()

status                                            message
0    ham                      Ok lar... Joking wif u oni...
1   spam  Free entry in 2 a wkly comp to win FA Cup fina...
2    ham  U dun say so early hor... U c already then say...
3    ham  Nah I don't think he goes to usf, he lives aro...
4   spam  FreeMsg Hey there darling it's been 3 week's n...

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
label_encoder = LabelEncoder()

In [10]:
X = mydata.iloc[:,1].values

In [11]:
Y = mydata.iloc[:,0].values

In [12]:
Y_encoded = label_encoder.fit_transform(Y)

In [13]:
Y_encoded

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

# ham =0, spam =1

In [14]:
x_train,x_test,y_train,y_test = train_test_split(X,Y_encoded,test_size=0.2)

# Count Vectorizer

In [15]:
cv = CountVectorizer()

In [16]:
x_traincv = cv.fit_transform(x_train)

In [17]:
x_testcv = cv.transform(x_test)

In [18]:
a = x_traincv.toarray()

In [19]:
len(a)

4456

In [20]:
a.shape

(4456, 7660)

In [21]:
mymnb = MultinomialNB()

In [22]:
mymodel = mymnb.fit(x_traincv,y_train)

In [23]:
yp = mymodel.predict(x_testcv)

In [24]:
ya = y_test

In [25]:
from sklearn import metrics

In [26]:
metrics.accuracy_score(ya,yp)

0.98744394618834086

# Random input mail to check whether the mail is spam or not

In [27]:
input_mail = ['Hiii how are u']

In [248]:
input_mail_cv = cv.transform(input_mail)

In [249]:
mymodel.predict(input_mail_cv)

array([0])

# Output 0 signifies that the input mail is not spam

# Tdidf Vectorizer

In [250]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [251]:
tv = TfidfVectorizer(stop_words='english')

In [252]:
x_traintv = tv.fit_transform(x_train)

In [253]:
b = x_traintv.toarray()

In [254]:
len(b)

4456

In [255]:
tv.inverse_transform(x_traintv[0])

[array(['dear'], 
       dtype='<U28')]

In [256]:
type(x_traintv)

scipy.sparse.csr.csr_matrix

In [257]:
x_traintv.shape

(4456, 7508)

In [258]:
x_testtv = tv.transform(x_test)

In [259]:
mymnb_tv = MultinomialNB()

In [260]:
mymodel_tv = mymnb_tv.fit(x_traintv,y_train)

In [261]:
yp = mymodel_tv.predict(x_testtv)

In [262]:
type(x_traintv)

scipy.sparse.csr.csr_matrix

In [263]:
ya = y_test

In [264]:
from sklearn import metrics

In [265]:
metrics.accuracy_score(ya,yp)

0.97399103139013454

# Random input mail to check whether the mail is spam or not

In [266]:
input_mail = ['Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. ']

In [267]:
input_mail_tv = tv.transform(input_mail)

In [268]:
mymodel_tv.predict(input_mail_tv)

array([1])

# Output 0 signifies that the input mail is not spam