In [1]:
import  numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [2]:
df=pd.read_csv(r"C:\Users\Rads Gupta\Desktop\SMSSpamCollection",sep="\t", names=["Status","Message"])

In [3]:
df.head()

Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
len(df)

5572

In [5]:
df.shape

(5572, 2)

In [6]:
len(df[df.Status=="spam"])

747

In [7]:
df.loc[df["Status"]=="ham","Status"]=1
df.loc[df["Status"]=="spam","Status"]=0

In [8]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [9]:
features=df["Message"]
target=df["Status"]

In [10]:
xtrain,xtest,ytrain,ytest=train_test_split(features,target,test_size=0.2,random_state=4)

In [11]:
xtrain.shape

(4457,)

In [12]:
cv=CountVectorizer()

In [13]:
xtraincv=cv.fit_transform(xtrain)

In [14]:
xtraincv

<4457x7762 sparse matrix of type '<class 'numpy.int64'>'
	with 59022 stored elements in Compressed Sparse Row format>

In [15]:
a=xtraincv.toarray()

In [16]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
len(a[0])

7762

In [18]:
cv.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'me', 'now',
        'online', 'or', 'replying', 'sleeping', 'spys', 'take', 'to', 'wat',
        'you'], 
       dtype='<U27')]

In [19]:
xtrain.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [20]:
mnb=MultinomialNB()

In [34]:
ytrain=ytrain.astype(int)

In [35]:
ytrain

1457    1
472     1
2481    0
243     1
1413    1
2726    1
3184    1
2308    0
2106    1
1473    1
3813    1
5394    1
4308    1
1009    1
3933    1
2759    1
2355    1
4664    1
1719    1
2236    1
570     1
2626    0
2339    1
874     1
354     1
2652    1
1901    1
2673    1
1670    1
4310    1
       ..
3394    1
3633    1
3720    0
1054    1
5493    1
4270    1
4802    1
56      0
2470    1
3785    1
149     1
2581    0
4279    1
1024    1
1411    1
1588    1
5246    1
946     1
5433    1
5047    1
2871    0
3678    1
1082    1
4489    1
456     1
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int32

In [36]:
mnb.fit(xtraincv,ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [37]:
xtestcv=cv.transform(xtest)

In [38]:


xtestcv


<1115x7762 sparse matrix of type '<class 'numpy.int64'>'
	with 14115 stored elements in Compressed Sparse Row format>

In [39]:
yp=mnb.predict(xtestcv)

In [40]:
yp

array([1, 1, 1, ..., 1, 1, 0])

In [41]:
y=np.array(ytest)

In [42]:
y

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [43]:
yp-y

array([0, 0, 0, ..., 0, 0, 0], dtype=object)

In [44]:
count=0

In [45]:

for i in range (len(yp)):
    if yp[i]==y[i]:
         count=count+1

In [46]:
count

1092

In [47]:
len(yp)

1115

In [48]:
count/len(yp)

0.979372197309417