In [1]:

import pandas as pd

In [2]:
mydata=pd.read_excel(r"C:\Users\Rads Gupta\Downloads\DataSets-master\DataSets-master\wine.xlsx")

 mydata=pd.read_excel(r"C:\Users\Rads Gupta\Downloads\DataSets-master\DataSets-master\wine.xlsx",names=["abc","def",.......)

In [29]:
mydata

Class  Alcohol  Malic Acid   Ash  Alcalinity of Ash  Magnesium  \
0        1    14.23        1.71  2.43               15.6        127   
1        1    13.20        1.78  2.14               11.2        100   
2        1    13.16        2.36  2.67               18.6        101   
3        1    14.37        1.95  2.50               16.8        113   
4        1    13.24        2.59  2.87               21.0        118   
5        1    14.20        1.76  2.45               15.2        112   
6        1    14.39        1.87  2.45               14.6         96   
7        1    14.06        2.15  2.61               17.6        121   
8        1    14.83        1.64  2.17               14.0         97   
9        1    13.86        1.35  2.27               16.0         98   
10       1    14.10        2.16  2.30               18.0        105   
11       1    14.12        1.48  2.32               16.8         95   
12       1    13.75        1.73  2.41               16.0         89   
13       1    14.75        1.73  2.39               11.4         91   
14       1    14.38        1.87  2.38               12.0        102   
15       1    13.63        1.81  2.70               17.2        112   
16       1    14.30        1.92  2.72               20.0        120   
17       1    13.83        1.57  2.62               20.0        115   
18       1    14.19        1.59  2.48               16.5        108   
19       1    13.64        3.10  2.56               15.2        116   
20       1    14.06        1.63  2.28               16.0        126   
21       1    12.93        3.80  2.65               18.6        102   
22       1    13.71        1.86  2.36               16.6        101   
23       1    12.85        1.60  2.52               17.8         95   
24       1    13.50        1.81  2.61               20.0         96   
25       1    13.05        2.05  3.22               25.0        124   
26       1    13.39        1.77  2.62               16.1         93   
27       1    13.30        1.72  2.14               17.0         94   
28       1    13.87        1.90  2.80               19.4        107   
29       1    14.02        1.68  2.21               16.0         96   
..     ...      ...         ...   ...                ...        ...   
148      3    13.32        3.24  2.38               21.5         92   
149      3    13.08        3.90  2.36               21.5        113   
150      3    13.50        3.12  2.62               24.0        123   
151      3    12.79        2.67  2.48               22.0        112   
152      3    13.11        1.90  2.75               25.5        116   
153      3    13.23        3.30  2.28               18.5         98   
154      3    12.58        1.29  2.10               20.0        103   
155      3    13.17        5.19  2.32               22.0         93   
156      3    13.84        4.12  2.38               19.5         89   
157      3    12.45        3.03  2.64               27.0         97   
158      3    14.34        1.68  2.70               25.0         98   
159      3    13.48        1.67  2.64               22.5         89   
160      3    12.36        3.83  2.38               21.0         88   
161      3    13.69        3.26  2.54               20.0        107   
162      3    12.85        3.27  2.58               22.0        106   
163      3    12.96        3.45  2.35               18.5        106   
164      3    13.78        2.76  2.30               22.0         90   
165      3    13.73        4.36  2.26               22.5         88   
166      3    13.45        3.70  2.60               23.0        111   
167      3    12.82        3.37  2.30               19.5         88   
168      3    13.58        2.58  2.69               24.5        105   
169      3    13.40        4.60  2.86               25.0        112   
170      3    12.20        3.03  2.32               19.0         96   
171      3    12.77        2.39  2.28               19.5         86   
172      3    14.16        2.

In [4]:
i=mydata.iloc[:,1:]

In [5]:
t=mydata.iloc[:,0]

In [6]:
t.shape

(178,)

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
xtrain,xtest,ytrain,ytest=train_test_split(i,t,test_size=0.3,random_state=20)

In [47]:
#Preprocessing

In [39]:
from sklearn.preprocessing import StandardScaler


In [40]:
myscale=StandardScaler()

In [50]:
X_xtrain=xtrain
X_xtest=xtest

In [51]:
myscale.fit(X_xtrain)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [52]:
X_xtrain.head(3)

Alcohol  Malic Acid   Ash  Alcalinity of Ash  Magnesium  Total Phenols  \
175    13.27        4.28  2.26               20.0        120           1.59   
143    13.62        4.95  2.35               20.0         92           2.00   
146    13.88        5.04  2.23               20.0         80           0.98   

     Flavanoids  Nonflavanoid Phenols  Proanthocyanins  Color intensity   Hue  \
175        0.69                  0.43             1.35             10.2  0.59   
143        0.80                  0.47             1.02              4.4  0.91   
146        0.34                  0.40             0.68              4.9  0.58   

     Diluted wines  Proline  
175           1.56      835  
143           2.05      550  
146           1.33      415

In [53]:
type(X_xtrain)

pandas.core.frame.DataFrame

In [54]:
type(xtrain)

pandas.core.frame.DataFrame

In [55]:
X_xtrain=myscale.transform(X_xtrain)

In [67]:
type(X_xtrain)

numpy.ndarray

In [56]:
X_xtest=myscale.transform(X_xtest)

In [57]:
round(X_xtest.mean())

-0.0

In [9]:

from sklearn.neighbors import KNeighborsClassifier

In [10]:
kn=KNeighborsClassifier(n_neighbors=1)

In [11]:
mymodel=kn.fit(xtrain,ytrain
              )

In [12]:
yp=mymodel.predict(xtest)

In [13]:
from sklearn import metrics

In [14]:
metrics.accuracy_score(ytest,yp)

0.7407407407407407

In [15]:
#how to drop a column


In [16]:
i1=mydata.drop(["Class"],axis=1)

In [17]:
i1.head(0)

Empty DataFrame
Columns: [Alcohol, Malic Acid, Ash, Alcalinity of Ash, Magnesium, Total Phenols, Flavanoids, Nonflavanoid Phenols, Proanthocyanins, Color intensity, Hue, Diluted wines, Proline]
Index: []

In [18]:
from sklearn.naive_bayes import GaussianNB

In [19]:
gnb=GaussianNB()

In [20]:
mymodel1=gnb.fit(xtrain,ytrain)

In [21]:
yp1=mymodel1.predict(xtest)

In [22]:
from sklearn import metrics

In [23]:
metrics.accuracy_score(ytest,yp1)

0.98148148148148151

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
mnb=MultinomialNB()

In [26]:
mymodel2=mnb.fit(xtrain,ytrain)

In [27]:
yp2=mymodel2.predict(xtest)

In [28]:
metrics.accuracy_score(ytest,yp2)

0.85185185185185186

# USING MLP CLASSIFIER

In [30]:
from sklearn.neural_network import MLPClassifier

In [58]:
mlp=MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [60]:
mymodel3=mlp.fit(X_xtrain,ytrain)

In [64]:
yp4=mymodel3.predict(X_xtest)

In [65]:
from sklearn import metrics

In [66]:
metrics.accuracy_score(ytest,yp4)

0.98148148148148151

In [68]:
from sklearn.metrics import classification_report,confusion_matrix

In [69]:
classification_report(ytest,yp4)

'             precision    recall  f1-score   support\n\n          1       1.00      1.00      1.00        15\n          2       1.00      0.96      0.98        27\n          3       0.92      1.00      0.96        12\n\navg / total       0.98      0.98      0.98        54\n'

In [70]:
confusion_matrix(ytest,yp4)

array([[15,  0,  0],
       [ 0, 26,  1],
       [ 0,  0, 12]])

In [71]:
#more than 2 classes that is y Multi layer perceptron.used

In [72]:
len(mymodel3.coefs_) #dominating features

4

In [75]:
mymodel3.coefs_ 

[array([[  5.27777481e-01,   6.78490387e-01,  -3.90329553e-01,
          -1.90194901e-01,   1.32741093e-01,  -3.34569986e-01,
          -7.86961047e-02,  -2.80902098e-01,  -5.31717056e-01,
           6.31069409e-02,   2.28967706e-02,   1.76888219e-01,
           5.76522907e-02],
        [  1.34255886e-01,  -1.73127051e-01,  -4.62290278e-01,
           1.99153350e-01,  -3.92793867e-01,   5.45693631e-01,
          -1.17824291e-01,   1.97552137e-02,  -5.97926840e-02,
          -3.98416294e-01,   1.53319702e-01,  -1.79321184e-01,
          -2.80578353e-01],
        [ -5.22004846e-02,  -1.03352175e-01,  -2.68173115e-01,
           2.94815377e-01,  -3.92809673e-01,   4.91704278e-01,
          -5.12930308e-01,  -2.84217588e-01,  -5.67331805e-01,
          -3.07581959e-01,  -1.57549178e-01,  -4.68684789e-01,
           3.67792877e-01],
        [  1.64906918e-01,  -1.12533691e-01,   3.89721625e-01,
           5.73076876e-01,   8.94804152e-02,   5.63272893e-01,
           5.43915478e-01,   2.023

In [76]:
mymodel3.intercepts_[0] #bias

array([-0.1511429 ,  0.532899  ,  0.47521486, -0.11317428,  0.36085162,
        0.03378713,  0.13529297,  0.169396  ,  0.01355455,  0.50102698,
        0.60025486,  0.08308897,  0.32768979])

In [77]:
mymodel3.coefs_[0]  #weight at each node

array([[  5.27777481e-01,   6.78490387e-01,  -3.90329553e-01,
         -1.90194901e-01,   1.32741093e-01,  -3.34569986e-01,
         -7.86961047e-02,  -2.80902098e-01,  -5.31717056e-01,
          6.31069409e-02,   2.28967706e-02,   1.76888219e-01,
          5.76522907e-02],
       [  1.34255886e-01,  -1.73127051e-01,  -4.62290278e-01,
          1.99153350e-01,  -3.92793867e-01,   5.45693631e-01,
         -1.17824291e-01,   1.97552137e-02,  -5.97926840e-02,
         -3.98416294e-01,   1.53319702e-01,  -1.79321184e-01,
         -2.80578353e-01],
       [ -5.22004846e-02,  -1.03352175e-01,  -2.68173115e-01,
          2.94815377e-01,  -3.92809673e-01,   4.91704278e-01,
         -5.12930308e-01,  -2.84217588e-01,  -5.67331805e-01,
         -3.07581959e-01,  -1.57549178e-01,  -4.68684789e-01,
          3.67792877e-01],
       [  1.64906918e-01,  -1.12533691e-01,   3.89721625e-01,
          5.73076876e-01,   8.94804152e-02,   5.63272893e-01,
          5.43915478e-01,   2.02340780e-01,   7.800